# Generated by Django 5.0.6 on 2024-06-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0003_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_id",
                to="book_app.author",
            ),
        ),
        migrations.AlterModelTable(
            name="author",
            table="authors",
        ),
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
    ]
